services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: studyApplication
    ports:
      - "5433:5432"
    networks:
      - application-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin@123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - application-network

networks:
  application-network:
    driver: bridge