spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5433/studyApplication
    username: postgres
    password: 123456
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true